# Generated by Django 3.0.4 on 2020-09-15 19:44

import account.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_auto_20200915_2240'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopuser',
            managers=[
                ('objects', account.managers.CustomUserManager()),
            ],
        ),
    ]
