# Generated by Django 3.0.4 on 2020-09-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_auto_20200915_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_superuser',
            field=models.BooleanField(default=False,
                                      help_text='Designates that this user has all permissions without explicitly assigning them.',
                                      verbose_name='superuser status'),
        ),
    ]
