# Generated by Django 3.0.4 on 2020-10-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_varificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varificationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
