# Generated by Django 3.0.4 on 2020-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
