# Generated by Django 3.0.4 on 2020-07-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_5',
        ),
        migrations.AddField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='comment',
                                    to='catalog.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default=None, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.PositiveIntegerField(help_text='%'),
        ),
    ]
