# Generated by Django 3.0.4 on 2020-07-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_query_name='parameter', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='params',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_query_name='parameter', to='catalog.Item'),
        ),
    ]
