# Generated by Django 3.0.4 on 2020-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0004_auto_20200721_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='category',
        ),
        migrations.AddField(
            model_name='params',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_query_name='parameter', to='catalog.Category'),
        ),
    ]
