# Generated by Django 3.0.4 on 2020-07-23 15:24

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_auto_20200721_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default=None, max_length=2000, null=True)),
                ('rating', models.IntegerField(validators=[catalog.models.rating_check])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='comment',
                                           to='catalog.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Params',
            new_name='Param',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
